CREATE TABLE IF NOT EXISTS monument_designs (
  id SERIAL PRIMARY KEY,
  monument_image TEXT NOT NULL,
  elements JSONB NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);